[WIP]: Consistency between hosted agents for holo
holochain/tryorama pull request #36
Opened 2020-09-01 02:17 UTC by zo-el

2020-09-21 16:18 UTC, zippy requested changes
This all looks great, but I think we really also want to ensure that zome calls can be made to hosted players, not just admin calls.  And it looks like the regular zome call function that's available on Player isn't available on HostedPlayer.

2020-09-21 16:18 UTC, zippy commented on test/e2e/test-dynamic-on.ts
> +  test('test with hostedPlayers instances and run consistency', async t => {
This test doesn't include a zome-call through to the hosted players?

2021-12-02 20:25 UTC, maackle commented
can this be closed?

2022-05-27 00:54 UTC, jost-s commented
@zo-el This looks out of date. Can it be closed?

2022-05-27 01:07 UTC, closed without merging